---
# File: tasks/install_packages_RedHat.yml - OS packages for Red Hat
- name: "Ensure that {{ hubot_admin }} is present"
  become: true
  user:
    name: "{{ hubot_admin }}"
    createhome: true
    state: present

- name: Install EPEL repo.
  become: True
  become_user: root
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: ansible_pkg_mgr == 'yum'

- name: Import EPEL GPG key
  become: True
  become_user: root
  rpm_key:
    key: "{{ epel_repo_gpg_key }}"
    state: present

# - name: install Development tools package group
#   become: True
#   become_user: root
#   yum: name="@Development tools" state=present
#   when: ansible_pkg_mgr == 'yum'
#   changed_when: False

- name: Install RedHat packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_prerequisites[ansible_os_family]}}"
- set_fact:
    redis_server: redis


- name: Install pip packages
  become: true
  pip:
    name: "{{ item }}"
  with_items: "{{python_pips}}"

- name: Install Node Version Manager
  become: True
  become_user: "{{ hubot_admin }}"
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ hubot_nvm_dir }}"
    accept_hostkey: True
  tags:
    - node_nvm

- name: Install Node.js
  become: True
  become_user: "{{ hubot_admin }}"
  shell: "source {{ hubot_nvm_dir }}/nvm.sh && nvm install {{ hubot_node_version }}"
  args:
    creates: "{{ hubot_node_dir }}"
    executable: /bin/bash
  changed_when: False
  tags:
    - node_packages
