---
# File: tasks/install_packages_RedHat.yml - OS packages for Red Hat

- name: Install EPEL repo.
  become: True
  become_user: root
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: ansible_pkg_mgr == 'yum'

- name: Import EPEL GPG key
  become: True
  become_user: root
  rpm_key:
    key: "{{ epel_repo_gpg_key }}"
    state: present

# - name: install Development tools package group
#   become: True
#   become_user: root
#   yum: name="@Development tools" state=present
#   when: ansible_pkg_mgr == 'yum'
#   changed_when: False

- name: Install RedHat packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ system_prerequisites[ansible_os_family]}}"
- set_fact:
    redis_server: redis


- name: Install pip packages
  become: true
  pip:
    name: "{{ item }}"
  with_items: "{{python_pips}}"
