---
- name: Start Redis
  become: True
  become_user: root
  service:
    name: "{{ redis_server }}"
    state: started

- name: Install service init script
  become: True
  become_user: root
  template:
    src: hubot.init.j2
    dest: /etc/init.d/hubot
    mode: "0755"
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version < "7")
  notify:
    - enable hubot
    - restart hubot

- name: Install systemd unit
  become: True
  become_user: root
  template:
    src: hubot.service.j2
    dest: /etc/systemd/system/hubot.service
    mode: "0755"
  when: (ansible_os_family == "Debian" and ansible_distribution_major_version >= "15") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version > "6")
  notify:
    - enable hubot
    - restart hubot
  tags:
    - hubot_service
